services:
  db:
    image: docker.io/library/postgres:18
    healthcheck:
      test: pg_isready -U myuser -d mydb
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      RUSTFS_ACCESS_KEY: plm-rustfs-user
      RUSTFS_SECRET_KEY: plm-rustfs-secret
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_LOG: info
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/logs
    restart: unless-stopped

volumes:
  rustfs-data:
  rustfs-logs:
