CREATE TABLE IF NOT EXISTS vendor_quote (
    id UUID PRIMARY KEY,
    product_vendor_sourcing_id UUID NOT NULL,
    quote_number VARCHAR(100) NOT NULL,
    version_number INTEGER NOT NULL,
    currency_code VARCHAR(3) NOT NULL,
    incoterm VARCHAR(30),
    unit_cost NUMERIC(19, 4) NOT NULL,
    moq INTEGER NOT NULL,
    lead_time_days INTEGER NOT NULL,
    sample_lead_time_days INTEGER,
    material_cost NUMERIC(19, 4),
    labor_cost NUMERIC(19, 4),
    overhead_cost NUMERIC(19, 4),
    logistics_cost NUMERIC(19, 4),
    duty_cost NUMERIC(19, 4),
    packaging_cost NUMERIC(19, 4),
    margin_percent NUMERIC(5, 2),
    total_cost NUMERIC(19, 4),
    capacity_per_month INTEGER,
    payment_terms VARCHAR(255),
    valid_from DATE,
    valid_to DATE,
    compliance_notes VARCHAR(1000),
    sustainability_notes VARCHAR(1000),
    status VARCHAR(30) NOT NULL,
    created_by VARCHAR(255),
    submitted_by VARCHAR(255),
    submitted_at timestamptz,
    reviewed_by VARCHAR(255),
    reviewed_at timestamptz,
    approval_comment VARCHAR(1000),
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at timestamptz,
    deleted_by VARCHAR(255),
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT fk_vendor_quote_link FOREIGN KEY (product_vendor_sourcing_id) REFERENCES product_vendor_sourcing(id),
    CONSTRAINT uq_vendor_quote_version UNIQUE (product_vendor_sourcing_id, quote_number, version_number),
    CONSTRAINT chk_vendor_quote_unit_cost_non_negative CHECK (unit_cost >= 0),
    CONSTRAINT chk_vendor_quote_moq_non_negative CHECK (moq >= 0),
    CONSTRAINT chk_vendor_quote_lead_time_non_negative CHECK (lead_time_days >= 0),
    CONSTRAINT chk_vendor_quote_sample_lead_time_non_negative CHECK (sample_lead_time_days IS NULL OR sample_lead_time_days >= 0),
    CONSTRAINT chk_vendor_quote_material_cost_non_negative CHECK (material_cost IS NULL OR material_cost >= 0),
    CONSTRAINT chk_vendor_quote_labor_cost_non_negative CHECK (labor_cost IS NULL OR labor_cost >= 0),
    CONSTRAINT chk_vendor_quote_overhead_cost_non_negative CHECK (overhead_cost IS NULL OR overhead_cost >= 0),
    CONSTRAINT chk_vendor_quote_logistics_cost_non_negative CHECK (logistics_cost IS NULL OR logistics_cost >= 0),
    CONSTRAINT chk_vendor_quote_duty_cost_non_negative CHECK (duty_cost IS NULL OR duty_cost >= 0),
    CONSTRAINT chk_vendor_quote_packaging_cost_non_negative CHECK (packaging_cost IS NULL OR packaging_cost >= 0),
    CONSTRAINT chk_vendor_quote_margin_non_negative CHECK (margin_percent IS NULL OR margin_percent >= 0),
    CONSTRAINT chk_vendor_quote_total_cost_non_negative CHECK (total_cost IS NULL OR total_cost >= 0),
    CONSTRAINT chk_vendor_quote_capacity_non_negative CHECK (capacity_per_month IS NULL OR capacity_per_month >= 0),
    CONSTRAINT chk_vendor_quote_validity CHECK (valid_from IS NULL OR valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX vendor_quote_link_idx ON vendor_quote(product_vendor_sourcing_id);
CREATE INDEX vendor_quote_status_idx ON vendor_quote(status);
CREATE INDEX vendor_quote_deleted_idx ON vendor_quote(deleted);
CREATE INDEX vendor_quote_validity_idx ON vendor_quote(valid_from, valid_to);
