ALTER TABLE product
    ADD COLUMN IF NOT EXISTS lifecycle VARCHAR(255),
    ADD COLUMN IF NOT EXISTS assortment VARCHAR(255),
    ADD COLUMN IF NOT EXISTS buy_plan VARCHAR(255),
    ADD COLUMN IF NOT EXISTS store_cost NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS retail_cost NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS margin NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS buyer VARCHAR(255),
    ADD COLUMN IF NOT EXISTS set_week INTEGER,
    ADD COLUMN IF NOT EXISTS inspiration VARCHAR(1000);
